# Book.toml for converting Markdown to HTML

# Basic information about the book
[book]
title = "Full-Stack Developer Course"
author = "Sidhartha"
description = "A comprehensive course for aspiring full-stack developers."
language = "en"
keywords = ["full-stack", "developer", "course", "programming", "web development"]
multilingual = false

# Build settings
[build]
build-dir = "output"  # Directory for output HTML files
target = "html"  # Target format

# Output settings
[output]
highlight = true  # Enable syntax highlighting
search = { enabled = true }  # Enable search functionality

[output.default-theme]
default-theme = "dark"  # Theme for output
optional = true

# Enable or disable features
[features]
mathjax = true  # If you need math support
syntax_highlighting = true  # For code highlighting
