[book]
title = "Full Stack Developer Course"
author = "Sidhartha"
description = "A comprehensive course on HTML, CSS, JavaScript, Node.js, and more."
language = "en"
multilingual = false

[output.html]
default-theme = "dark"
highlight = true
additional-css = ["custom.css"]
search = { enabled = true }

[build]
create-missing = true
mathjax-support = false

[output.html.playground]
copy-button = true

# Optional: Draft configuration to exclude in-progress sections
[draft]
include = false
